print('digite algo e daremos informações sobre')
NA = input('Digite algo:')
print(type(NA))
print('É um alfanumérico?',NA.isalnum())
print('É um alfebético?',NA.isalpha())
print('É um decimal?',NA.isdecimal())
print('É um digito?',NA.isdigit())
print('É identificavel?',NA.isidentifier())
print('É composto apenas de letras minúsculas?',NA.islower())
print('É um número?',NA.isnumeric())
print('É possivel imprimir?',NA.isprintable())
print('É somente espaço?',NA.isspace())
print('Esta capitalizado?',NA.istitle())
print('É composto apenas de letras maiúsculas?',NA.isupper())